export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_RESPONSE = 'GET_CATEGORY_RESPONSE';

export const GET_TASKS = 'GET_TASKS';
export const GET_TASKS_RESPONSE = 'GET_TASKS_RESPONSE';

export const CREATE_TASK = 'CREATE_TASK';
export const GET_TASK = 'GET_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const GET_NEW_TASK = 'GET_NEW_TASK';

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_RESPONSE = 'DELETE_TASK_RESPONSE';
export const UPDATE_TASK_RESPONSE = 'UPDATE_TASK_RESPONSE';

export const GET_TASK_RESPONSE = 'GET_TASK_RESPONSE';
export const CREATE_TASK_RESPONSE = 'CREATE_TASK_RESPONSE';

export const CONFIRMATION_POPUP = 'CONFIRMATION_POPUP';
export const CONFIRMATION_POPUP_CLOSE = 'CONFIRMATION_POPUP_CLOSE';